# Generated by Django 6.0 on 2026-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='query',
            name='employee',
        ),
        migrations.AddField(
            model_name='query',
            name='employe_mailid',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='title',
            field=models.CharField(default='test@gmail.com'),
            preserve_default=False,
        ),
    ]
